Add option to download run-time generated API, update CMake action

diff --git a/.github/workflows/cmake_example.yml b/.github/workflows/cmake_example.yml
--- a/.github/workflows/cmake_example.yml
+++ b/.github/workflows/cmake_example.yml
@@ -37,3 +37,38 @@ jobs:
           echo "example program not found"
           exit 1
         fi
+
+  zig_build:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ${{github.workspace}}/program/cpp/project
+    env:
+      CC: zig cc -target riscv64-linux-musl
+      CXX: zig c++ -target riscv64-linux-musl
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Install dependencies
+      run: |
+        sudo apt update
+        sudo apt install -y git cmake zip wget xz-utils
+        git submodule update --init --recursive --depth=1
+        # Install Zig
+        wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2414+ba37a4369.tar.xz
+        tar -xf zig-linux-x86_64-0.14.0-dev.2414+ba37a4369.tar.xz
+
+    - name: Build the example program
+      run: |
+        export PATH=$PWD/zig-linux-x86_64-0.14.0-dev.2414+ba37a4369:$PATH
+        cmake -B build -DCMAKE_BUILD_TYPE=Release -DSTRIPPED=ON
+        cmake --build build --parallel 8
+
+    - name: Verify the example program exists
+      working-directory: ${{github.workspace}}/program/cpp/project/build
+      run: |
+        if [ ! -f sandbox_program.elf ]; then
+          echo "example program not found"
+          exit 1
+        fi
